[package]
name = "minreq"
version = "0.1.2"
authors = ["Jens Pitkanen <jens@neon.moe>"]
description = "Simple, minimal-dependency HTTP client"
documentation = "https://docs.rs/minreq"
homepage = "https://github.com/neonmoe/minreq"
repository = "https://github.com/neonmoe/minreq"
readme = "README.md"
keywords = ["http", "client", "request"]
categories = ["web-programming::http-client"]
license = "ISC"

[badges]
travis-ci = { repository = "neonmoe/minreq", branch = "0.1.2" }
codecov = { repository = "neonmoe/minreq", branch = "0.1.2" }
maintenance = { status = "actively-developed" }

[dependencies]
rustls = { version = "0.12", optional = true }
webpki-roots = { version = "0.14", optional = true }
webpki = { version = "0.18.0-alpha", optional = true }

[dev-dependencies]
tiny_http = "0.5"

[features]
default = []

https = ["rustls", "webpki-roots", "webpki"]
